deploy:
  needs: build
  runs-on: ubuntu-latest
  
  steps:
    - name: Download WAR file
      uses: actions/download-artifact@v3
      with:
        name: java-app
        path: target

    - name: Deploy WAR via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Debugging the value of HOSTNAME
        echo "Using HOSTNAME: $HOSTNAME"
        ssh-keyscan -H $HOSTNAME >> ~/.ssh/known_hosts
        scp -i ~/.ssh/id_rsa target/*.war ubuntu@$HOSTNAME:/home/ubuntu/
    
    - name: Copy WAR file to Tomcat webapps
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.SSH_HOST }}
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@$HOSTNAME 'sudo cp /home/ubuntu/*.war /var/lib/tomcat9/webapps/'
